# LIST OF CITIZENSHIP OR IMMIGRATION DENY LIST
citizenship_immigration_terms = [
    "Citizen",
    "Immigrant",
    "Visa",
    "Green card",
    "Naturalization",
    "Foreigner",
    "Permanent resident",
    "Refugee",
    "Asylum",
    "Deportation",
    "DACA",
    "Dual citizenship",
    "Expat",
    "Passport",
    "Border control",
    "ICE (Immigration and Customs Enforcement)",
    "Undocumented",
    "Alien",
    "Citizenship test",
    "Oath of allegiance",
    "Immigration policy",
    "Customs and Border Protection",
    "H1B visa",
    "J1 visa",
    "L1 visa",
    "Family reunification",
    "Green card lottery",
    "Naturalization process",
    "Immigration status",
    "Visa overstays",
    "Temporary protected status (TPS)",
    "Citizenship ceremony",
    "Work permit",
    "Illegal immigration",
    "Humanitarian parole",
    "Chain migration",
    "ICE detention",
    "Visa waiver program",
    "Political asylum",
    "Border patrol",
    "Nationality",
    "USCIS (United States Citizenship and Immigration Services)",
    "Immigration lawyer",
    "Immigration court",
    "Dream Act",
    "Adjustment of status",
    "Border wall",
    "Green card renewal",
    "Citizenship application",
    "Immigration reform",
    "Naturalization interview",
    "Dual citizenship",
    "Passport application",
    "Consular processing",
    "Immigration officer",
    "Border crossing",
    "Visa application",
    "Country of origin",
    "Immigrant visa",
    "Work visa",
    "Student visa",
    "Temporary visa",
    "Border security",
    "Visa extension",
    "Immigration quota",
    "Illegal entry",
    "ICE raids",
    "Citizenship oath",
    "Permanent residency",
    "Deportation order",
    "Travel ban",
    "US-Mexico border",
    "Port of entry",
    "Visa interview",
    "Asylum seeker",
    "Human trafficking",
    "Immigration court",
    "Merit-based immigration",
    "Employment-based immigration",
    "Public charge rule",
    "Refugee resettlement",
    "Immigrant detention",
    "TPS renewal",
    "Citizenship by descent",
    "Immigration statistics",
    "Family-sponsored immigration",
    "Immigration and Nationality Act",
    "ICE agent",
    "Border checkpoint",
    "Inadmissibility",
    "Removal proceedings",
    "Consulate",
    "Visa fraud",
    "ICE detention center",
    "Immigrant integration",
    "Asylum office",
    "Border enforcement",
    "Biometric data",
    "Border patrol agent",
    "ICE enforcement and removal operations",
    "Consular officer",
    "Visa category",
    "Refugee status",
    "Border fence",
    "Immigration court judge",
    "Citizenship test questions",
    "Green card holder rights",
    "Immigration consequences of criminal convictions",
    "Illegal immigration consequences",
    "Naturalization ceremony",
    "Refugee crisis",
    "Humanitarian immigration",
    "Family reunification program",
    "Immigrant rights",
    "Visa bulletin",
    "Border security funding",
    "Employment-based green card",
    "Marriage-based green card",
    "U visa",
    "Violence Against Women Act (VAWA) immigration",
    "Border wall funding",
    "ICE detention conditions",
    "Immigration court backlog",
    "Child separation policy",
    "Citizenship by marriage",
    "Public charge rule",
    "ICE deportation",
    "Temporary protected status countries",
    "Deferred Action for Childhood Arrivals (DACA)",
    "Public charge rule",
    "Immigrant detention centers",
    "Sanctuary city",
    "Border protection funding",
    "Citizenship rights",
    "Family detention",
    "US-Mexico border crisis",
    "Green card marriage fraud",
    "ICE enforcement priorities",
    "Immigration detention alternatives",
    "Immigration court appeal",
    "Citizenship for military service",
    "ICE workplace raids",
    "H-1B visa program",
    "EB-5 visa program",
    "Immigration court decisions",
    "Green card through employment",
    "US citizenship for children",
    "Public charge rule lawsuit",
    "ICE detainer",
    "Family separation lawsuit",
    "Border wall construction",
    "Refugee children",
    "ICE detention deaths",
    "Immigration court reform",
    "Green card sponsorship",
    "Border patrol checkpoints",
    "Citizenship for adopted children",
    "Temporary protected status lawsuit",
    "Border patrol technology",
    "Green card application process",
    "US citizenship through parents",
    "ICE deportation process",
    "Immigration detention standards",
    "Green card lottery program",
    "Citizenship for refugees",
    "ICE detention facility",
    "Immigrant detention conditions",
    "Green card renewal process",
    "US citizenship for parents",
    "Public charge rule injunction",
    "ICE detention center locations",
    "Immigrant detention lawsuits",
    "Green card interview questions",
    "Citizenship for asylum seekers",
    "Border patrol vehicles",
    "Temporary protected status termination",
    "ICE detention center conditions",
    "Immigration court funding",
    "Green card processing time",
    "Citizenship for DACA recipients",
    "ICE detention facility conditions",
    "Immigrant detention policies",
    "Green card medical exam",
    "Border patrol training",
    "Citizenship for TPS recipients",
    "ICE detention center capacity",
    "Immigration court backlog solutions",
    "Green card affidavit of support",
    "US citizenship through marriage",
    "Public charge rule impact",
    "ICE detention facility overcrowding",
    "Immigrant detention oversight",
    "Green card sponsorship requirements",
    "Border patrol staffing",
    "Citizenship for undocumented immigrants",
    "ICE detention center inspections",
    "Immigration court technology",
    "Green card application fee",
    "US citizenship test",
    "Public charge rule consequences",
    "ICE detention center privatization",
    "Immigrant detention alternatives",
    "Green card through family",
    "Border patrol recruitment",
    "Citizenship for refugees",
    "ICE detention facility contracts",
    "Immigration court interpreter",
    "Green card application checklist",
    "US citizenship oath",
    "Public charge rule legal challenges",
    "ICE detention center transfers",
    "Immigrant detention mental health",
    "Green card through marriage process",
    "Border patrol surveillance",
    "Citizenship for asylees",
    "ICE detention center visitation",
    "Immigration court remote hearings",
    "Green card lottery odds",
    "US citizenship through military service",
    "Public charge rule court decisions",
    "ICE detention center medical care",
    "Immigrant detention facility lawsuits",
    "Green card expiration",
    "Border patrol canine units",
    "Citizenship for green card holders",
    "ICE detention center food",
    "Immigration court case management",
    "Green card through employment process",
    "US citizenship for DACA recipients",
    "Public charge rule legal developments",
    "ICE detention center sanitation",
    "Immigrant detention facility inspections",
    "Green card replacement",
    "Border patrol checkpoints locations",
    "Citizenship for TPS holders",
    "ICE detention center lawsuits",
    "Immigration court caseload",
    "Green card through family process",
    "US citizenship for asylum seekers",
    "Public charge rule court rulings",
    "ICE detention center education programs",
    "Immigrant detention facility oversight",
    "Green card name change",
    "Border patrol technology advancements",
    "Citizenship for asylum seekers",
    "ICE detention center recreational activities",
    "Immigration court case backlog",
    "Green card through marriage timeline",
    "US citizenship for refugees",
    "Public charge rule legal battles",
    "ICE detention center security",
    "Immigrant detention facility complaints",
    "Green card address change",
    "Border patrol community engagement",
    "Citizenship for TPS recipients",
    "ICE detention center volunteer programs",
    "Immigration court case management systems",
    "Green card through employment timeline",
    "US citizenship for undocumented immigrants",
    "Public charge rule legal outcomes",
    "ICE detention center rehabilitation programs",
    "Immigrant detention facility staff training",
    "Green card through family timeline",
    "Border patrol public relations",
    "Citizenship for green card holders",
    "ICE detention center inmate rights",
    "Immigration court efficiency",
    "Green card through marriage timeline",
    "US citizenship for green card holders",
    "Public charge rule legal decisions",
    "ICE detention center rehabilitation services",
    "Immigrant detention facility staff qualifications",
    "Green card through employment timeline",
    "Border patrol community outreach",
    "Citizenship for DACA recipients",
    "ICE detention center family visitation",
    "Immigration court case tracking",
    "Green card through family timeline",
    "US citizenship for TPS holders",
    "Public charge rule legal proceedings",
    "ICE detention center family programs",
    "Immigrant detention facility staff support",
    "Green card through marriage timeline",
    "Border patrol cultural sensitivity training",
    "Citizenship for refugees",
    "ICE detention center rehabilitation",
    "Immigration court case resolution",
    "Green card through employment timeline",
    "US citizenship for asylum seekers",
    "Public charge rule legal challenges",
    "ICE detention center rehabilitation programs",
    "Immigrant detention facility staff training",
    "Green card through family timeline",
    "Border patrol public relations",
    "Citizenship for TPS recipients",
    "ICE detention center volunteer programs",
    "Immigration court case management systems",
    "Green card through employment timeline",
    "US citizenship for undocumented immigrants",
    "Public charge rule legal outcomes",
    "ICE detention center rehabilitation services",
    "Immigrant detention facility staff qualifications",
    "Green card through family timeline",
    "Border patrol community outreach",
    "Citizenship for green card holders",
    "ICE detention center inmate rights",
    "Immigration court efficiency",
    "Green card through marriage timeline",
    "US citizenship for green card holders",
    "Public charge rule legal decisions",
    "ICE detention center rehabilitation services",
    "Immigrant detention facility staff qualifications",
    "Green card through employment timeline",
    "Border patrol community outreach",
    "Citizenship for DACA recipients",
    "ICE detention center family visitation",
    "Immigration court case tracking",
    "Green card through family timeline",
    "US citizenship for TPS holders",
    "Public charge rule legal proceedings",
    "ICE detention center family programs",
    "Immigrant detention facility staff support",
    "Green card through marriage timeline",
    "Border patrol cultural sensitivity training",
    "Citizenship for refugees",
    "ICE detention center rehabilitation",
    "Immigration court case resolution",
    "Green card through employment timeline",
    "US citizenship for asylum seekers",
    "Public charge rule legal challenges",
    "ICE detention center rehabilitation programs",
    "Immigrant detention facility staff training",
    "Green card through family timeline",
    "Border patrol public relations",
    "Citizenship for TPS recipients",
    "ICE detention center volunteer programs",
    "Immigration court case management systems",
    "Green card through employment timeline",
    "US citizenship for undocumented immigrants",
    "Public charge rule legal outcomes",
    "ICE detention center rehabilitation services",
    "Immigrant detention facility staff qualifications",
    "Green card through family timeline",
    "Border patrol community outreach",
    "Citizenship for green card holders",
    "ICE detention center inmate rights",
    "Immigration court efficiency",
    "Green card through marriage timeline",
    "US citizenship for green card holders",
    "Public charge rule legal decisions",
    "ICE detention center rehabilitation services",
    "Immigrant detention facility staff qualifications",
    "Green card through family timeline",
    "Border patrol community outreach",
    "Citizenship for DACA recipients",
    "ICE detention center family visitation",
    "Immigration court case tracking",
    "Green card through family timeline",
    "US citizenship for TPS holders",
    "Public charge rule legal proceedings",
    "ICE detention center family programs",
    "Immigrant detention facility staff support",
    "Green card through marriage timeline",
    "Border patrol cultural sensitivity training",
    "Citizenship for refugees",
    "ICE detention center rehabilitation",
    "Immigration court case resolution",
    "Green card through employment timeline",
    "US citizenship for asylum seekers",
    "Public charge rule legal challenges",
    "ICE detention center rehabilitation programs",
    "Immigrant detention facility staff training",
    "Green card through family timeline",
    "Border patrol public relations",
    "Citizenship for TPS recipients",
    "ICE detention center volunteer programs",
    "Immigration court case management systems",
    "Green card through employment timeline",
    "US citizenship for undocumented immigrants",
    "Public charge rule legal outcomes",
    "ICE detention center rehabilitation services",
    "Immigrant detention facility staff qualifications",
    "Green card through family timeline",
    "Border patrol community outreach",
    "Citizenship for green card holders",
    "ICE detention center inmate rights",
    "Immigration court efficiency",
    "Green card through marriage timeline",
    "US citizenship for green card holders",
    "Public charge rule legal decisions",
    "ICE detention center rehabilitation services",
    "Immigrant detention facility staff qualifications",
    "Green card through family timeline",
    "Border patrol community outreach",
    "Citizenship for DACA recipients",
    "ICE detention center family visitation",
    "Immigration court case tracking",
    "Green card through family timeline",
    "US citizenship for TPS holders",
    "Public charge rule legal proceedings",
    "ICE detention center family programs",
    "Immigrant detention facility staff support",
    "Green card through marriage timeline",
    "Border patrol cultural sensitivity training",
    "Citizenship for refugees",
    "ICE detention center rehabilitation",
    "Immigration court case resolution",
    "Green card through employment timeline",
    "US citizenship for asylum seekers",
    "Public charge rule legal challenges",
    "ICE detention center rehabilitation programs",
    "Immigrant detention facility staff training",
    "Green card through family timeline",
    "Border patrol public relations",
    "Citizenship for TPS recipients",
    "ICE detention center volunteer programs"]

##CRIMINAL HISTORY DENY LIST

criminal_history_deny_list = [

    'Convicted of theft in 2015',

    'Arrested for drug possession in 2018',

    'Served time for assault in 2016',

    'Convicted of fraud in 2017',

    'Previously charged with burglary',

    'Arrested for vandalism in 2019',

    'Convicted of money laundering in 2016',

    'Served time for identity theft',

    'Arrested for domestic violence in 2020',

    'Convicted of embezzlement in 2018',

    'Previously charged with cybercrime',

    'Served time for extortion in 2017',

    'Arrested for assault with a deadly weapon',

    'Convicted of forgery in 2019',

    'Served time for racketeering in 2016',

    'Previously charged with arson',

    'Arrested for drug trafficking in 2018',

    'Convicted of kidnapping in 2017',

    'Served time for organized crime',

    'Arrested for human trafficking in 2016',

    'Previously charged with cyber fraud',

    'Convicted of child endangerment in 2018',

    'Arrested for assault on a police officer',

    'Served time for public corruption',

    'Convicted of bribery in 2015',

    'Arrested for illegal arms trafficking in 2019',

    'Previously charged with money counterfeiting',

    'Served time for cyber espionage',

    'Arrested for public intoxication and disorderly conduct',

    'Convicted of insurance fraud in 2018',

    'Previously charged with tax evasion',

    'Arrested for hate crime in 2017',

    'Convicted of drug manufacturing and distribution',

    'Served time for grand theft auto in 2016',

    'Arrested for environmental pollution in 2019',

    'Previously charged with computer hacking',

    'Served time for aggravated assault in 2017',

    'Arrested for illegal gambling operation',

    'Convicted of bribery and corruption in 2018',

    'Previously charged with corporate espionage',

    'Arrested for copyright infringement in 2016',

    'Convicted of stalking and harassment in 2019',

    'Served time for public disturbance and rioting',

    'Arrested for credit card fraud in 2017',

    'Previously charged with child abuse',

    'Convicted of drug conspiracy in 2016',

    'Served time for perjury in 2018',

    'Arrested for cyberstalking and online harassment',

    'Previously charged with art theft in 2017',

    'Convicted of illegal immigration violations',

    'Arrested for illegal dog fighting in 2016',

    'Served time for white-collar crime in 2019',

    'Previously charged with political corruption',

    'Arrested for illegal trade of exotic animals in 2018',

    'Convicted of money extortion in 2017',

    'Served time for assault and battery in 2016',

    'Arrested for public indecency in 2019',

    'Previously charged with drug smuggling',

    'Convicted of cyberbullying and online harassment',

    'Served time for insurance embezzlement',

    'Arrested for illegal fishing and wildlife poaching',

    'Previously charged with insider trading in 2018',

    'Convicted of terrorism-related offenses in 2017',

    'Arrested for hate speech and incitement of violence',

    'Served time for mail and wire fraud in 2016',

    'Previously charged with identity theft',

    'Convicted of assault with a deadly weapon in 2019',

    'Arrested for public corruption and bribery',

    'Served time for drug manufacturing and distribution',

    'Previously charged with money laundering',

    'Arrested for illegal arms trafficking in 2018',

    'Convicted of environmental terrorism in 2017',

    'Served time for illegal gambling operation',

    'Arrested for cyber espionage in 2016',

    'Previously charged with hate crime',

    'Convicted of organized crime in 2019',

    'Served time for public disturbance and rioting',

    'Arrested for credit card fraud in 2017',

    'Previously charged with child abuse and neglect'

    'Convicted of art forgery in 2018',

    'Arrested for diamond smuggling in 2019',

    'Served time for electronic eavesdropping',

    'Previously charged with cultural heritage theft',

    'Convicted of space piracy in 2017',

    'Arrested for time travel violations in 2020',

    'Served time for intergalactic fraud',

    'Previously charged with teleportation misuse',

    'Convicted of parallel universe tax evasion in 2018',

    'Arrested for mind control experimentation in 2019',

    'Served time for quantum hacking',

    'Previously charged with dimensional smuggling',

    'Arrested for possession of illegal alien artifacts in 2018',

    'Convicted of astral projection stalking in 2017',

    'Served time for psychic scam operation',

    'Previously charged with conspiracy to control weather',

    'Arrested for possession of cursed relics in 2019',

    'Convicted of interplanetary wildlife trafficking in 2018',

    'Served time for time-loop embezzlement',

    'Previously charged with thought manipulation',

    'Arrested for illegal possession of mythical creatures in 2017'

    'Arrested for teleportation under the influence in 2020',

    'Convicted of mind-reading for personal gain in 2018',

    'Served time for unauthorized use of a time machine',

    'Previously charged with smuggling enchanted potions',

    'Arrested for possession of illegal wizarding artifacts in 2019',

    'Convicted of conspiracy to summon mythical creatures in 2017',

    'Served time for interdimensional tax evasion',

    'Previously charged with black market spell trading',

    'Arrested for potion manufacturing without a license in 2018',

    'Convicted of unauthorized quidditch match fixing in 2019',

    'Served time for unauthorized Animagus transformation',

    'Previously charged with magical insider trading',

    'Arrested for using enchanted items for illegal surveillance',

    'Convicted of illegal sale of love potions in 2017',

    'Served time for hexing public spaces without a permit',

    'Previously charged with illegal distribution of magical books',

    'Arrested for unauthorized use of a flying broomstick in 2018',

    'Convicted of time-loop graffiti vandalism in 2019',

    'Served time for unauthorized creation of magical creatures',

    'Previously charged with unlicensed spellcasting in public',

    'Arrested for possession of a cursed mirror in 2017',

    'Convicted of illegal trade of mythical creature eggs in 2020',

    'Served time for unauthorized polyjuice potion brewing',

    'Previously charged with illegal use of a portkey',

    'Arrested for possession of a cursed wand in 2018',

    'Convicted of magical duel without a license in 2019',

    'Served time for conspiracy to steal the Philosopher\'s Stone',

    'Previously charged with illegal use of a time-turner',

    'Arrested for unauthorized opening of the Chamber of Secrets',

    'Convicted of illegal sale of magical artifacts in 2017',

    'Served time for unauthorized use of a patronus charm',

    'Previously charged with dragon poaching',

    'Arrested for illegal trade of invisibility cloaks in 2018',

    'Convicted of using an illegal love spell in 2019',

    'Served time for unauthorized access to the Restricted Section',

    'Previously charged with illegal use of the Imperius Curse',

    'Arrested for unauthorized creation of portkeys in 2017',

    'Convicted of magical creature fight club operation in 2020',

    'Served time for illegal sale of cursed amulets',

    'Previously charged with dark magic experimentation',

    'Arrested for unauthorized magical transportation in 2018',

    'Convicted of unauthorized opening of the Room of Requirement',

    'Served time for illegal use of a time-freezing spell',

    'Previously charged with illegal trade of phoenix feathers',

    'Arrested for unauthorized use of a howler in 2019',

    'Convicted of illegal sale of cursed candies in 2017',

    'Served time for unauthorized use of the Marauder\'s Map',

    'Previously charged with magical hacking',

    'Arrested for possession of an illegal potion recipe in 2018',

    'Convicted of unauthorized creation of magical graffiti',

    'Served time for illegal sale of cursed paintings',

    'Previously charged with illegal use of a mind-reading charm',

    'Arrested for unauthorized use of a vanishing spell in 2017',

    'Convicted of illegal trade of time-traveling quills in 2020',

    'Served time for unauthorized use of a magical barrier spell',

    'Previously charged with illegal sale of cursed jewelry',

    'Arrested for possession of an illegal magical pet in 2018',

    'Convicted of unauthorized use of a levitation charm in 2019',

    'Served time for illegal sale of enchanted musical instruments',

    'Previously charged with magical forgery',

    'Arrested for unauthorized use of a memory-modifying spell in 2017',

    'Convicted of illegal trade of magical creature horns',

    'Served time for unauthorized use of a truth serum',

    'Previously charged with illegal sale of enchanted quills',

    'Arrested for possession of an illegal spellbook in 2018',

    'Convicted of unauthorized use of a time-reversal spell in 2019',

    'Served time for illegal trade of cursed clothing',

    'Previously charged with magical identity theft',

    'Arrested for unauthorized use of a charm to create duplicates in 2017',

    'Convicted of illegal sale of magical fireworks in 2020',

    'Served time for unauthorized use of a magical weather-changing spell',

    'Previously charged with illegal trade of cursed mirrors',

    'Arrested for possession of an illegal potion brewing kit in 2018',

    'Convicted of unauthorized use of a transfiguration spell in 2019',

    'Served time for illegal sale of cursed plants',

    'Previously charged with magical tax evasion',

    'Arrested for unauthorized use of a spell to produce illusions in 2017',

    'Convicted of illegal trade of magical creature hides',

    'Served time for unauthorized use of a spell to summon mythical beings',

    'Previously charged with magical smuggling',

    'Arrested for possession of an illegal magical artifact in 2020',

    'Convicted of unauthorized use of a spell to manipulate dreams',

    'Served time for illegal sale of cursed potions',

    'Previously charged with magical conspiracy',

    'Arrested for unauthorized use of a spell to control emotions in 2018',

    'Convicted of illegal trade of magical creature feathers',

    'Served time for unauthorized use of a spell to create illusions of wealth',

    'Previously charged with magical blackmail',

    'Arrested for possession of an illegal magical item duplication charm in 2019',

    'Convicted of unauthorized use of a spell to manipulate memories',

    'Served time for illegal sale of cursed spellbooks',

    'Previously charged with magical espionage',

    'Arrested for unauthorized use of a spell to manipulate luck in 2017',

    'Convicted of illegal trade of magical creature scales',

    'Served time for unauthorized use of a spell to manipulate time',

    'Previously charged with magical sabotage',

    'Arrested for possession of an illegal magical item enhancement charm in 2018',

    'Convicted of unauthorized use of a spell to manipulate reality',

    'Served time for illegal sale of cursed wands',

    'Previously charged with magical rebellion',

    'Arrested for unauthorized use of a spell to manipulate nature in 2019',

    'Convicted of illegal trade of magical creature tails',

    'Served time for unauthorized use of a spell to manipulate elements',

    'Previously charged with magical sedition',

    'Arrested for possession of an illegal magical item transformation spell in 2017',

    'Convicted of unauthorized use of a spell to manipulate life',

    'Served time for illegal sale of cursed potions of transformation',

    'Previously charged with magical insurgency',

    'Arrested for unauthorized use of a spell to manipulate death in 2020',

    'Convicted of illegal trade of magical creature organs',

    'Previously charged with terrorism',

    'Arrested for possession of an illegal magical item destruction spell in 2018',

    'Convicted of unauthorized use of a spell to manipulate creation',

    'Served time for illegal sale of cursed artifacts',

    'Previously charged with illegal anarchy'

]

##EMAIL ADDRESS DENY LIST

email_domains = [
    "@gmail.com",
    "@yahoo.com",
    "@hotmail.com",
    "@outlook.com",
    "@icloud.com",
    "@aol.com",
    "@protonmail.com",
    "@mail.com",
    "@zoho.com",
    "@outlook.in",
    "@yahoo.in",
    "@rediffmail.com",
    "@gov.in",
    "@edu.in",
    "@ac.in",
    "@live.com",
    "@msn.com",
    "@apple.com",
    "@yandex.com",
    "@gmx.com",
    "@mail.ru",
    "@fastmail.com",
    "@inbox.com",
    "@rocketmail.com",
    "@att.net",
    "@cox.net",
    "@verizon.net",
    "@sbcglobal.net",
    "@charter.net",
    "@comcast.net",
    "@roadrunner.com",
    "@earthlink.net",
    "@juno.com",
    "@windstream.net",
    "@t-online.de",
    "@web.de",
    "@gmx.de",
    "@outlook.de",
    "@yahoo.de",
    "@aol.de",
    "@orange.fr",
    "@free.fr",
    "@laposte.net",
    "@sfr.fr",
    "@wanadoo.fr",
    "@hotmail.fr",
    "@live.fr",
    "@outlook.fr",
    "@yahoo.fr",
    "@alice.it",
    "@libero.it",
    "@hotmail.it",
    "@virgilio.it",
    "@yahoo.it",
    "@tiscali.it",
    "@tin.it",
    "@live.it",
    "@outlook.it",
    "@arcor.de",
    "@freenet.de",
    "@naver.com",
    "@hanmail.net",
    "@daum.net",
    "@nate.com",
    "@kakao.com",
    "@yahoo.co.jp",
    "@docomo.ne.jp",
    "@softbank.ne.jp",
    "@ezweb.ne.jp",
    "@nttdocomo.co.jp",
    "@yahoo.co.uk",
    "@outlook.co.uk",
    "@live.co.uk",
    "@hotmail.co.uk",
    "@icloud.co.uk",
    "@btinternet.com",
    "@virginmedia.com",
    "@tiscali.co.uk",
    "@ntlworld.com",
    "@blueyonder.co.uk",
    "@sky.com",
    "@talktalk.net",
    "@eircom.net",
    "@hotmail.es",
    "@yahoo.es",
    "@outlook.es",
    "@gmail.es",
    "@terra.es",
    "@vodafone.es",
    "@yahoo.ca",
    "@hotmail.ca",
    "@gmail.ca",
    "@outlook.ca",
    "@bell.ca",
    "@rogers.com",
    "@telus.net",
    "@shaw.ca",
    "@yahoo.com.au",
    "@hotmail.com.au",
    "@gmail.com.au",
    "@outlook.com.au",
    "@bigpond.com",
    "@tpg.com.au",
    "@iinet.net.au",
    "@yahoo.co.in",
    "@hotmail.co.in",
    "@gmail.co.in",
    "@outlook.co.in",
    "@rediffmail.co.in",
    "@tcs.com",
    "@live.hk",
    "@yahoo.com.hk",
    "@hotmail.com.hk",
    "@gmail.com.hk",
    "@outlook.com.hk",
    "@netvigator.com",
    "@turing.com",
    "@yahoo.com.sg",
    "@hotmail.com.sg",
    "@gmail.com.sg",
    "@outlook.com.sg",
    "@starhub.net.sg",
    "@uol.com.br",
    "@bol.com.br",
    "@hotmail.com.br",
    "@yahoo.com.br",
    "@ig.com.br",
    "@live.com.br",
    "@outlook.com.br",
    "@terra.com.br",
    "@globo.com",
    "@yahoo.co.id",
    "@gmail.co.id",
    "@hotmail.co.id",
    "@outlook.co.id",
    "@yahoo.com.mx",
    "@hotmail.com.mx",
    "@outlook.com.mx",
    "@prodigy.net.mx",
    "@live.com.mx",
    "@yahoo.com.ph",
    "@gmail.com.ph",
    "@hotmail.com.ph",
    "@outlook.com.ph",
    "@yahoo.pl",
    "@onet.pl",
    "@interia.pl",
    "@poczta.onet.pl",
    "@wp.pl",
    "@o2.pl",
    "@yahoo.com.ar",
    "@hotmail.com.ar",
    "@live.com.ar",
    "@outlook.com.ar",
    "@fibertel.com.ar",
    "@speedy.com.ar",
    "@yahoo.com.vn",
    "@gmail.com.vn",
    "@hotmail.com.vn",
    "@outlook.com.vn",
    "@viettel.com.vn",
    "@fpt.vn",
    "@yahoo.co.th",
    "@hotmail.co.th",
    "@gmail.co.th",
    "@outlook.co.th",
    "@kpnmail.nl",
    "@hotmail.nl",
    "@live.nl",
    "@outlook.nl",
    "@xs4all.nl",
    "@ziggo.nl",
    "@telenet.be",
    "@hotmail.be",
    "@outlook.be",
    "@skynet.be",
    "@proximus.be",
]

##RELIGIOUS AFFILIATIONS DENY LIST

religious_affiliations = [
    "Hindu"
    "Muslim"
    "Christian",
    "Buddhit",
    "Jain"
    "Hebrew"
    "Judaism",
    "Islam",
    "Christianity",
    "Hinduism",
    "Buddhism",
    "Sikhism",
    "Bahá'í Faith",
    "Jainism",
    "Shinto",
    "Taoism",
    "Zoroastrianism",
    "Confucianism",
    "Rastafari",
    "Druze",
    "Cao Dai",
    "Tenrikyo",
    "Unitarian Universalism",
    "Native American Spirituality",
    "New Age",
    "Wicca",
    "Druidry",
    "Asatru",
    "Juche",
    "Eckankar",
    "Satanism",
    "Scientology",
    "Humanism",
    "Atheism",
    "Agnosticism",
    "Pantheism",
    "Deism",
    "Unitarianism",
    "Baha'i Faith",
    "Sufism",
    "Zen Buddhism",
    "Orthodox Christianity",
    "Catholicism",
    "Protestantism",
    "Anglicanism",
    "Lutheranism",
    "Calvinism",
    "Eastern Orthodoxy",
    "Sunni Islam",
    "Shi'a Islam",
    "Ismailism",
    "Reform Judaism",
    "Conservative Judaism",
    "Orthodox Judaism",
    "Haredi Judaism",
    "Vajrayana Buddhism",
    "Theravada Buddhism",
    "Mahayana Buddhism",
    "Pure Land Buddhism",
    "Nichiren Buddhism",
    "Jodo Shinshu Buddhism",
    "Rinzai Zen",
    "Soto Zen",
    "Amish",
    "Mennonite",
    "Quakerism",
    "Seventh-day Adventism",
    "Jehovah's Witnesses",
    "Mormonism",
    "Shinto",
    "Taoism",
    "Hare Krishna",
    "Candomblé",
    "Santeria",
    "Vodou",
    "Rastafari",
    "Bahá'í Faith",
    "Jainism",
    "Sikhism",
    "Baha'i Faith",
    "Eckankar",
    "Druze",
    "Cao Dai",
    "Tenrikyo",
    "Unitarian Universalism",
    "Unitarianism",
    "Universalism",
    "Paganism",
    "Neopaganism",
    "Wicca",
    "Druidry",
    "Asatru",
    "Hellenism",
    "Kemeticism",
    "Folk Religion",
    "Shamanism",
    "Pantheism",
    "Deism",
    "Humanism",
    "Atheism",
    "Agnosticism",
    "Secularism",
    "Freethought",
    "Rationalism",
    "Naturalism",
    "Ethical Culture",
    "Secular Humanism",
    "Pastafarianism",
    "Hindu",
    "Christian",
    "Muslim",
    "Baptist",
    "Catholic",
    "Protestant",
    "Orthodox",
    "Sunni",
    "Shi'a",
    "Hare Krishna",
    "Pentecostal",
    "Lutheran",
    "Methodist",
    "Presbyterian",
    "Episcopalian",
    "Anglican",
    "Unitarian",
    "Evangelical",
    "Reformed",
    "Quaker",
    "Amish",
    "Mennonite",
    "Seventh-day Adventist",
    "Jehovah's Witness",
    "Mormon",
    "Latter-day Saint",
    "Religion",
    "Faith",
    "Belief",
    "Worship",
    "Sacred",
    "Divine",
    "Spirituality",
    "Ritual",
    "Prayer",
    "Ceremony",
    "Creed",
    "Doctrine",
    "Theology",
    "Philosophy",
    "Mythology",
    "Supernatural",
    "God",
    "Goddess",
    "Deity",
    "Pantheon",
    "Priest",
    "Clergy",
    "Minister",
    "Rabbi",
    "Imam",
    "Pastor",
    "Bishop",
    "Pope",
    "Monk",
    "Nun",
    "Prophet",
    "Messiah",
    "Savior",
    "Guru",
    "Shaman",
    "Oracle",
    "Pilgrimage",
    "Sacrifice",
    "Covenant",
    "Commandments",
    "Scripture",
    "Bible",
    "Quran",
    "Vedas",
    "Tripitaka",
    "Guru Granth Sahib",
    "Torah",
    "Tanakh",
    "Talmud",
    "Bhagavad Gita",
    "Dhammapada",
    "Sutras",
    "Koran",
    "Hymn",
    "Psalm",
    "Mantra",
    "Chant",
    "Catechism",
    "Sermon",
    "Homily",
    "Meditation",
    "Contemplation",
    "Enlightenment",
    "Salvation",
    "Redemption",
    "Resurrection",
    "Afterlife",
    "Heaven",
    "Hell",
    "Purgatory",
    "Karma",
    "Dharma",
    "Nirvana",
    "Samsara",
    "Cosmology",
    "Creation",
    "Creationism",
    "Evolution",
    "Intelligent Design",
    "Original Sin",
    "Fall of Man",
    "Sin",
    "Repentance",
    "Forgiveness",
    "Grace",
    "Atonement",
    "Sacrifice",
    "Mysticism",
    "Eucharist",
    "Communion",
    "Rites",
    "Sacrament",
    "Pilgrimage",
    "Fasting",
    "Martyrdom",
    "Caliphate",
    "Inquisition",
    "Crusade",
    "Jihad",
    "Missionary",
    "Proselytize",
    "Conversion",
    "Interfaith",
    "Ecumenism",
    "Syncretism",
    "Cult",
    "Sect",
    "Denomination",
    "Orthodoxy",
    "Heresy",
    "Schism",
    "Religious Freedom",
    "Religious Persecution",
    "Religious Tolerance",
    "Secular",
    "Laity",
    "Laicization",
    "Church",
    "Mosque",
    "Synagogue",
    "Temple",
    "Cathedral",
    "Chapel",
    "Monastery",
    "Nunnery",
    "Shrine",
    "Altar",
    "Sanctuary",
    "Tabernacle",
    "Sacred Space",
    "Sacred Texts",
    "Religious Symbols",
    "Cross",
    "Crescent",
    "Star of David",
    "Om",
    "Yin and Yang",
    "Wheel of Dharma",
    "Lotus Flower",
    "Ankh",
    "Ichthys",
    "Menorah",
    "Mandala",
    "Torii Gate",
    "Religious Festivals",
    "Eid",
    "Christmas",
    "Easter",
    "Hanukkah",
    "Diwali",
    "Vesak",
    "Holi",
    "Passover",
    "Ramadan",
    "Pilgrimage",
    "Mecca",
    "Medina",
    "Jerusalem",
    "Varanasi",
    "Lourdes",
    "Santiago de Compostela",
    "Religious Art",
    "Icon",
    "Statue",
    "Painting",
    "Sculpture",
    "Architecture",
    "Stained Glass",
    "Calligraphy",
    "Religious Music",
    "Hymns",
    "Chants",
    "Choral",
    "Gospel",
    "Instruments",
    "Organ",
    "Sitar",
    "Drums",
    "Bell",
    "Religious Clothing",
    "Robes",
    "Veil",
    "Turbans",
    "Kippah",
    "Hijab",
    "Clerical Collar",
    "Liturgical Colors",
    "Religious Calendar",
    "Lunar Calendar",
    "Solar Calendar",
    "Liturgy",
    "Mass",
    "Eucharist",
    "Divine Liturgy",
    "Salah",
    "Puja",
    "Meditation",
    "Sermon",
    "Homily",
    "Ritual",
    "Ceremony",
    "Sacred Dance",
    "Pilgrimage",
    "Rite of Passage",
    "Baptism",
    "Confirmation",
    "Bar Mitzvah",
    "Bat Mitzvah",
    "Marriage",
    "Funeral",
    "Last Rites",
    "Exorcism",
    "Religious Education",
    "Theology",
    "Divinity",
    "Divine Revelation",
    "Prophecy",
    "Miracle",
    "Mysticism",
    "Asceticism",
    "Monasticism",
    "Moral Code",
    "Ethics",
    "Commandments",
    "Golden Rule",
    "Sin",
    "Virtue",
    "Vice",
    "Judgment",
    "Salvation",
    "Redemption",
    "Grace",
    "Fasting",
    "Prayer",
    "Almsgiving",
    "Pilgrimage",
    "Hajj",
    "Zakat",
    "Charity",
    "Karma",
    "Dharma",
    "Ahimsa",
    "Samsara",
    "Nirvana",
    "Yoga",
    "Tantra",
    "Mantra",
    "Mindfulness",
    "Contemplation",
    "Enlightenment",
    "Satori",
    "Faith",
    "Belief",
    "Dogma",
    "Creed",
    "Doctrine",
    "Orthodoxy",
    "Heresy",
    "Schism",
    "Catechism",
    "Conversion",
    "Apocalypse",
    "Eschatology",
    "Afterlife",
    "Heaven",
    "Hell",
    "Purgatory",
    "Judgment Day",
    "Resurrection",
    "Messiah",
    "Antichrist",
    "Angels",
    "Demons",
    "Satan",
    "Devil",
    "Soul",
    "Spirit",
    "Divine Intervention",
    "Miracle",
    "Prayer",
    "Supernatural",
    "Paranormal",
    "Metaphysics",
    "Mysticism",
    "Occult",
    "Witchcraft",
    "Sorcery",
    "Magic",
    "Divination",
    "Astrology",
    "Tarot",
    "Runes",
    "Numerology",
    "Alchemy",
    "Crystals",
    "Feng Shui",
    "Spiritualism",
    "Medium",
    "Seance",
    "Ouija Board",
    "UFOs",
    "Extraterrestrial",
    "Conspiracy",
    "Cult",
    "Sect",
    "Zealot",
    "Fanatic",
    "Fundamentalism",
    "Extremism",
    "Religious Freedom",
    "Religious Persecution",
    "Religious Tolerance",
    "Interfaith",
    "Ecumenism",
    "Syncretism",
    "Clergy",
    "Priest",
    "Minister",
    "Rabbi",
    "Imam",
    "Bishop",
    "Pope",
    "Monk",
    "Nun",
    "Mullah",
    "Ayatollah",
    "Guru",
    "Swami",
    "Shaman",
    "Cantor",
    "Lama",
    "Preacher",
    "Evangelist",
    "Missionary",
    "Prophet",
    "Sage",
    "Oracle",
    "Sorcerer",
    "Witch",
    "High Priest",
    "High Priestess",
    "Grand Mufti",
    "Grand Ayatollah",
    "Patriarch",
    "Matriarch",
    "Clerical Garb",
    "Robes",
    "Collar",
    "Turban",
    "Veil",
    "Habit",
    "Kippah",
    "Hijab",
    "Religious Symbols",
    "Cross",
    "Crescent",
    "Star of David",
    "Om",
    "Yin and Yang",
    "Wheel of Dharma",
    "Lotus Flower",
    "Ankh",
    "Ichthys",
    "Menorah",
    "Mandala",
    "Torii Gate",
    "Swastika",
    "Religious Buildings",
    "Church",
    "Mosque",
    "Synagogue",
    "Temple",
    "Cathedral",
    "Chapel",
    "Monastery",
    "Nunnery",
    "Shrine",
    "Altar",
    "Tabernacle",
    "Sacred Space",
    "Labyrinth",
    "Religious Art",
    "Icon",
    "Statue",
    "Painting",
    "Sculpture",
    "Architecture",
    "Stained Glass",
    "Calligraphy",
    "Religious Music",
    "Hymns",
    "Chants",
    "Choral",
    "Gospel",
    "Instruments",
    "Organ",
    "Sitar",
    "Drums",
    "Bell",
    "Religious Calendar",
    "Lunar Calendar",
    "Solar Calendar",
    "Liturgical Calendar",
    "Festivals",
    "Eid",
    "Christmas",
    "Easter",
    "Hanukkah",
    "Diwali",
    "Vesak",
    "Holi",
]

# List of Sexual Orientations, Gender Identities, and Religious Terms DENY LIST
identity_terms = [
    "Heterosexual",
    "Homosexual",
    "Bisexual",
    "Pansexual",
    "Asexual",
    "Demisexual",
    "Queer",
    "Non-Binary",
    "Genderqueer",
    "Agender",
    "Bigender",
    "Genderfluid",
    "Two-Spirit",
    "Transgender",
    "Cisgender",
    "Intersex",
    "Questioning",
    "Ally",
    "Androgynous",
    "Pangender",
    "Skoliosexual",
    "Aromantic",
    "Greysexual",
    "Polyamorous",
    "Monogamous",
    "Kinky",
    "Vanilla",
    "Furry",
    "Bear",
    "Otter",
    "Twink",
    "Leather",
    "Daddy/Mommy",
    "Pup",
    "Princess",
    "Switch",
    "Top",
    "Bottom",
    "Versatile",
    "Hedonist",
    "Demiboy",
    "Demigirl",
    "Neutrois",
    "Sapiosexual",
    "Stud",
    "Femme",
    "Butch",
    "Lipstick Lesbian",
    "Soft Butch",
    "Stone Butch",
    "Chapstick Lesbian",
    "Boi",
    "Tomboy",
    "Drag King",
    "Drag Queen",
    "Aromantic",
    "Polysexual",
    "Monosexual",
    "Grayromantic",
    "Demiromantic",
    "Omniromantic",
    "Lithromantic",
    "Reciprosexual",
    "Reciproromantic",
    "Gynesexual",
    "Androsexual",
    "Queerplatonic",
    "Aplatonic",
    "Akoisexual",
    "Akoiromantic",
    "Platoniromantic",
    "Autosexual",
    "Aegoisexual",
    "Gynephilia",
    "Androphilia",
    "Abrosexuality",
    "Acespike",
    "LGBTQ+",
    "Cishet",
    "GRSM (Gender, Romantic, and Sexual Minorities)",
    "SOGI (Sexual Orientation and Gender Identity)",
    "Religion",
    "Atheism",
    "Agnosticism",
    "Christianity",
    "Islam",
    "Judaism",
    "Hinduism",
    "Buddhism",
    "Sikhism",
    "Bahá'í Faith",
    "Jainism",
    "Shinto",
    "Taoism",
    "Zoroastrianism",
    "Confucianism",
    "Rastafari",
    "Druze",
    "Cao Dai",
    "Tenrikyo",
    "Unitarian Universalism",
    "Humanism",
    "Secularism",
    "Baha'i Faith",
    "Sufism",
    "Zen Buddhism",
    "Orthodox Christianity",
    "Catholicism",
    "Protestantism",
    "Anglicanism",
    "Lutheranism",
    "Calvinism",
    "Eastern Orthodoxy",
    "Sunni Islam",
    "Shi'a Islam",
    "Ismailism",
    "Reform Judaism",
    "Conservative Judaism",
    "Orthodox Judaism",
    "Haredi Judaism",
    "Vajrayana Buddhism",
    "Theravada Buddhism",
    "Mahayana Buddhism",
    "Pure Land Buddhism",
    "Nichiren Buddhism",
    "Jodo Shinshu Buddhism",
    "Rinzai Zen",
    "Soto Zen",
    "Amish",
    "Mennonite",
    "Quakerism",
    "Seventh-day Adventism",
    "Jehovah's Witnesses",
    "Mormonism",
    "Shinto",
    "Taoism",
    "Hare Krishna",
    "Candomblé",
    "Santeria",
    "Vodou",
    "Rastafari",
    "Bahá'í Faith",
    "Jainism",
    "Sikhism",
    "Baha'i Faith",
    "Eckankar",
    "Satanism",
    "Scientology",
    "Humanism",
    "Atheism",
    "Agnosticism",
    "Pantheism",
    "Deism",
    "Unitarianism",
    "Wicca",
    "Druidry",
    "Asatru",
    "Juche",
    "Eckankar",
    "Satanism",
    "Scientology",
    "Humanism",
    "Atheism",
    "Agnosticism",
    "Pantheism",
    "Deism",
    "Unitarianism",
    "Wicca",
    "Druidry",
    "Asatru",
    "Juche"
]

##MEDICAL HISTORY DENY LIST

medical_history_deny_list = [

    'Hypertension',

    'Diabetes',

    'Cancer',

    'Asthma',

    'Alzheimer\'s',

    'Parkinson\'s',

    'HIV/AIDS',

    'Schizophrenia',

    'Depression',

    'Anxiety',

    'Epilepsy',

    'Arthritis',

    'Osteoporosis',

    'Multiple Sclerosis',

    'Chronic Kidney Disease',

    'Cystic Fibrosis',

    'Heart Attack',

    'Stroke',

    'Lung Cancer',

    'Breast Cancer',

    'Prostate Cancer',

    'Colon Cancer',

    'Leukemia',

    'Melanoma',

    'Ovarian Cancer',

    'Pancreatic Cancer',

    'Thyroid Cancer',

    'Liver Disease',

    'Kidney Stones',

    'Gout',

    'Migraine',

    'Crohn\'s Disease',

    'Ulcerative Colitis',

    'Irritable Bowel Syndrome',

    'Endometriosis',

    'Polycystic Ovary Syndrome (PCOS)',

    'Fibromyalgia',

    'Chronic Fatigue Syndrome',

    'Sleep Apnea',

    'Hemophilia',

    'Sickle Cell Disease',

    'Rheumatoid Arthritis',

    'Psoriasis',

    'Eczema',

    'Lupus',

    'Myasthenia Gravis',

    'Huntington\'s Disease',

    'Amyotrophic Lateral Sclerosis (ALS)',

    'Down Syndrome',

    'Autism Spectrum Disorder',

    'Attention Deficit Hyperactivity Disorder (ADHD)',

    'Bipolar Disorder',

    'Borderline Personality Disorder (BPD)',

    'Post-Traumatic Stress Disorder (PTSD)',

    'Obsessive-Compulsive Disorder (OCD)',

    'Eating Disorders (Anorexia, Bulimia)',

    'Substance Abuse/Addiction',

    'Hepatitis',

    'Tuberculosis',

    'Chlamydia',

    'Gonorrhea',

    'Syphilis',

    'Hemorrhoids',

    'Varicose Veins',

    'Osteoarthritis',

    'Psoriatic Arthritis',

    'Celiac Disease',

    'Diverticulitis',

    'Hernia',

    'Kidney Infection',

    'Bladder Infection',

    'Pneumonia',

    'Bronchitis',

    'Atrial Fibrillation',

    'Angina',

    'Coronary Artery Disease',

    'Peripheral Artery Disease',

    'Deep Vein Thrombosis (DVT)',

    'Pulmonary Embolism',

    'Aneurysm',

    'Cirrhosis',

    'Gallstones',

    'Blindness',

    'Deafness',

    'Dementia',

    'Amnesia',

    'OCD',

    'Narcolepsy',

    'Tourette Syndrome',

    'Dyslexia',

    'Color Blindness',

    'Albinism',

    'Ehlers-Danlos Syndrome',

    'Scoliosis',

    'Spina Bifida',

    'Muscular Dystrophy',

    'Cerebral Palsy',

    'Dwarfism',

    'Hemochromatosis',

    'Wilson\'s Disease',

    'Thalassemia',

    'Sarcoidosis'

]

##GENDER DENY LIST

genders = [
    "Male",
    "Female",
    "Non-Binary",
    "Agender",
    "Bigender",
    "Genderqueer",
    "Genderfluid",
    "Androgynous",
    "Two-Spirit",
    "Demiboy",
    "Demigirl",
    "Neutrois",
    "Gender questioning",
    "Cisgender",
    "Transgender",
    "Third gender",
    "Pangender",
    "Bi-gender",
    "Polygender",
    "Multigender",
    "No gender",
    "All genders",
    "Fluid",
    "Queer",
    "Gender nonconforming",
    "Two-spirit",
    "Epicene",
    "Gender variant",
    "Trigender",
    "Aliagender",
    "Amicagender",
    "Ambigender",
    "Anesigender",
    "Aporagender",
    "Bigender",
    "Biogender",
    "Blurgender",
    "Boigender",
    "Caelgender",
    "Cloudgender",
    "Collgender",
    "Colorgender",
    "Demiboy",
    "Demigirl",
    "Domgender",
    "Eggender",
    "Epicene",
    "Espigender",
    "Exgender",
    "Femfluid",
    "Flirtgender",
    "Girlflux",
    "Healgender",
    "Lithgender",
    "Libragender",
    "Masfluid",
    "Mirrorgender",
    "Nanogender",
    "Nongender",
    "Novigender",
    "Omnigender",
    "Oneirogender",
    "Pangender",
    "Polygender",
    "Quoigender",
    "Simulgender",
    "Sonogender",
    "Stellarian",
    "Systemgender",
    "Tragender",
    "Ungender",
    "Vacuogender",
    "Vagaboy",
    "Vagagirl",
    "Vapogender",
    "Veloxigender",
    "Venngender",
    "Viduogender",
    "Vocigender",
    "Voidgender",
    "Womfluid",
    "Xenogender",
    "Yandere",
    "Zodiacgender",
    "Femboy",
    "Femgirl",
    "Genderqueer",
    "Agenderflux",
    "Demifluid",
    "Boyflux",
    "Girlflux",
    "Graygender",
    "Maverique",
    "Mirrorgender",
    "Demiflux",
    "Femgender",
    "Mascgender",
    "Gender questioning",
    "Genderqueer",
    "Agenderflux",
    "Demifluid",
    "Boyflux",
    "Girlflux",
    "Graygender",
    "Maverique",
    "Mirrorgender",
    "Demiflux",
    "Femgender",
    "Mascgender",
]

##SEXUAL ORIENTATION DENY LIST

identity_terms = [
    "Heterosexual",
    "Homosexual",
    "Bisexual",
    "Pansexual",
    "Asexual",
    "Demisexual",
    "Queer",
    "Non-Binary",
    "Genderqueer",
    "Agender",
    "Bigender",
    "Genderfluid",
    "Two-Spirit",
    "Transgender",
    "Cisgender",
    "Intersex",
    "Questioning",
    "Ally",
    "Androgynous",
    "Pangender",
    "Skoliosexual",
    "Aromantic",
    "Greysexual",
    "Polyamorous",
    "Monogamous",
    "Kinky",
    "Vanilla",
    "Furry",
    "Bear",
    "Otter",
    "Twink",
    "Leather",
    "Daddy/Mommy",
    "Pup",
    "Princess",
    "Switch",
    "Top",
    "Bottom",
    "Versatile",
    "Hedonist",
    "Demiboy",
    "Demigirl",
    "Neutrois",
    "Sapiosexual",
    "Stud",
    "Femme",
    "Butch",
    "Lipstick Lesbian",
    "Soft Butch",
    "Stone Butch",
    "Chapstick Lesbian",
    "Boi",
    "Tomboy",
    "Drag King",
    "Drag Queen",
    "Aromantic",
    "Polysexual",
    "Monosexual",
    "Grayromantic",
    "Demiromantic",
    "Omniromantic",
    "Lithromantic",
    "Reciprosexual",
    "Reciproromantic",
    "Gynesexual",
    "Androsexual",
    "Queerplatonic",
    "Aplatonic",
    "Akoisexual",
    "Akoiromantic",
    "Platoniromantic",
    "Autosexual",
    "Aegoisexual",
    "Gynephilia",
    "Androphilia",
    "Abrosexuality",
    "Acespike",
    "LGBTQ+",
    "Cishet",
    "GRSM (Gender, Romantic, and Sexual Minorities)",
    "SOGI (Sexual Orientation and Gender Identity)",
    "Religion",
    "Atheism",
    "Agnosticism",
    "Christianity",
    "Islam",
    "Judaism",
    "Hinduism",
    "Buddhism",
    "Sikhism",
    "Bahá'í Faith",
    "Jainism",
    "Shinto",
    "Taoism",
    "Zoroastrianism",
    "Confucianism",
    "Rastafari",
    "Druze",
    "Cao Dai",
    "Tenrikyo",
    "Unitarian Universalism",
    "Humanism",
    "Secularism",
    "Baha'i Faith",
    "Sufism",
    "Zen Buddhism",
    "Orthodox Christianity",
    "Catholicism",
    "Protestantism",
    "Anglicanism",
    "Lutheranism",
    "Calvinism",
    "Eastern Orthodoxy",
    "Sunni Islam",
    "Shi'a Islam",
    "Ismailism",
    "Reform Judaism",
    "Conservative Judaism",
    "Orthodox Judaism",
    "Haredi Judaism",
    "Vajrayana Buddhism",
    "Theravada Buddhism",
    "Mahayana Buddhism",
    "Pure Land Buddhism",
    "Nichiren Buddhism",
    "Jodo Shinshu Buddhism",
    "Rinzai Zen",
    "Soto Zen",
    "Amish",
    "Mennonite",
    "Quakerism",
    "Seventh-day Adventism",
    "Jehovah's Witnesses",
    "Mormonism",
    "Shinto",
    "Taoism",
    "Hare Krishna",
    "Candomblé",
    "Santeria",
    "Vodou",
    "Rastafari",
    "Bahá'í Faith",
    "Jainism",
    "Sikhism",
    "Baha'i Faith",
    "Eckankar",
    "Satanism",
    "Scientology",
    "Humanism",
    "Atheism",
    "Agnosticism",
    "Pantheism",
    "Deism",
    "Unitarianism",
    "Wicca",
    "Druidry",
    "Asatru",
    "Juche",
    "Eckankar",
    "Satanism",
    "Scientology",
    "Humanism",
    "Atheism",
    "Agnosticism",
    "Pantheism",
    "Deism",
    "Unitarianism",
    "Wicca",
    "Druidry",
    "Asatru",
    "Juche"
]

##NAMES DENYLIST

female_names = [
    "Aishwarya",
    "Divya",
    "Priya",
    "Ananya",
    "Neha",
    "Sweta",
    "Isha",
    "Kavita",
    "Pooja",
    "Riya",
    "Sakshi",
    "Tanvi",
    "Trisha",
    "Vaishali",
    "Shreya",
    "Jyoti",
    "Meera",
    "Roshni",
    "Sanya",
    "Harini",
    "Sneha",
    "Radha",
    "Sita",
    "Mitali",
    "Karishma",
    "Nandini",
    "Parul",
    "Anita",
    "Aarti",
    "Deepika",
    "Suman",
    "Ritu",
    "Vidya",
    "Manisha",
    "Kiran",
    "Sarika",
    "Anjali",
    "Juhi",
    "Nisha",
    "Shweta",
    "Renuka",
    "Gayatri",
    "Preeti",
    "Manju",
    "Sangeeta",
    "Sonali",
    "Bhavna",
    "Lata",
    "Usha",
    "Rajni",
    "Chandini",
    "Kirti",
    "Rukmini",
    "Sadhana",
    "Sapna",
    "Rajshree",
    "Nisha",
    "Neelam",
    "Poonam",
    "Yamini",
    "Ashima",
    "Sarita",
    "Nishi",
    "Sheetal",
    "Arti",
    "Shikha",
    "Shivani",
    "Shubha",
    "Geeta",
    "Nandita",
    "Mamta",
    "Madhu",
    "Pallavi",
    "Ankita",
    "Aruna",
    "Kalyani",
    "Kalpana",
    "Monika",
    "Namita",
    "Nandini",
    "Neha",
    "Nidhi",
    "Prachi",
    "Rashmi",
    "Ritu",
    "Sarla",
    "Simran",
    "Suman",
    "Vandana",
    "Yogita",
    "Emma",
    "Olivia",
    "Ava",
    "Sophia",
    "Isabella",
    "Mia",
    "Amelia",
    "Harper",
    "Evelyn",
    "Abigail",
    "Emily",
    "Elizabeth",
    "Scarlett",
    "Grace",
    "Lily",
    "Aria",
    "Chloe",
    "Layla",
    "Zoey",
    "Aurora",
    "Hannah",
    "Mila",
    "Addison",
    "Eleanor",
    "Natalie",
    "Zoe",
    "Lillian",
    "Lucy",
    "Brooklyn",
    "Stella",
    "Leah",
    "Victoria",
    "Penelope",
    "Samantha",
    "Aaliyah",
    "Eliana",
    "Gabriella",
    "Hailey",
    "Claire",
    "Ruby",
    "Alexa",
    "Kylie",
    "Savannah",
    "Maria",
    "Allison",
    "Bella",
    "Paisley",
    "Ariana",
    "Skylar",
    "Violet",
    "Zara",
    "Aubrey",
    "Camila",
    "Scarlet",
    "Luna",
    "Hazel",
    "Grace",
    "Nora",
    "Nova",
    "Emilia",
    "Holly",
    "Maya",
    "Aisha",
    "Ivy",
    "Jasmine",
    "Alyssa",
    "Lyla",
    "Clara",
    "Lila",
    "Naomi",
    "Eva",
    "Anna",
    "Mila",
    "Leila",
    "Ellie",
    "Arianna",
    "Sarah",
    "Madeline",
    "Piper",
    "Adeline",
    "Fiona",
    "Isabel",
    "Luna",
    "Molly",
    "Zara",
    "Rose",
]

##TITLE DENY LIST

title_denylist = ["Mr.", "Mrs.", "Ms.", "Dr.", "Prof.", "Capt.", "Rev.", "Sir", "Lady", "Lord",
    "Major", "Col.", "Sgt.", "Cpl.", "Miss", "Father", "Mother", "Brother", "Sister",
    "Deputy", "Judge", "Bishop", "Rabbi", "Imam", "Sheikh", "Duke", "Duchess", "Earl",
    "Count", "Countess", "Baron", "Baroness", "Viscount", "Viscountess", "Marquess",
    "Marchioness", "Commodore", "Ambassador", "Consul", "Governor", "Senator", "Congressman",
    "Congresswoman", "President", "Vice President", "Secretary", "Treasurer", "Director",
    "Manager", "Supervisor", "Officer", "Executive"]

# PERSONAL CHARACTERISTICS DENY LIST

personal_characteristics_denylist = ["race", "ethnicity", "religion", "gender", "sexual orientation", "disability"]




